#!/usr/bin/env bash

# initialize dotbot
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# Install dialog if it doesn't exist
if ! command -v dialog &> /dev/null; then
    sudo apt update -y
    sudo apt install dialog -y
fi

# user select modules to install
available_modules=$(
    find . -name "conf.yaml" \
    | cut -d "/" -f 2 \
    | sort \
    | awk '{print $1, "off"}'
)

modules=$(dialog \
    --title "Select modules" \
    --stdout \
    --no-items \
    --ok-label "Install modules" \
    --checklist "Select modules" 22 76 16 $available_modules
)

# Clear the screen after the dialog
clear

# Install selected modules
for module in $modules; do \
    CONFIG="$module/conf.yaml"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
done

